clone_depth: 1

#init:
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
    BUILD_NO: $(APPVEYOR_BUILD_NUMBER)
    BRANCH: $(APPVEYOR_REPO_BRANCH)
    REPO: $(APPVEYOR_REPO_NAME)
    matrix:
        - ARCH: x86_64
          ARCH_BIT: 64
          APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
          BUILD_DEPS_CMD: "/home/appveyor/projects/scopy/CI/appveyor/build_appveyor_flatpak.sh $BRANCH $REPO"
          BUILD_CMD: ""
          DEPLOY_FILE: "/home/appveyor/projects/scopy/Scopy.flatpak"
         
matrix:
    fast_finish: true

install:
    # Install Inno Setup
    - cmd: choco install InnoSetup
    - sh: docker version

build_script:
    - cmd: set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
    - cmd: "%BUILD_DEPS_CMD%"

    - sh: echo $BUILD_DEPS_CMD
    - sh: $BUILD_DEPS_CMD
    - sh: $BUILD_CMD

    - echo "### Push artifacts ... "
    - cmd: appveyor PushArtifact c:\scopy-%ARCH_BIT%bit.zip
    - cmd: appveyor PushArtifact C:\debug-%ARCH_BIT%bit.zip
   
    - cmd: appveyor PushArtifact %DEPLOY_FILE%
    - sh: if [[ $DEPLOY_FILE != "" ]]; then appveyor PushArtifact $DEPLOY_FILE; fi

#on_finish:
#    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
